export enum StatusCompraEnum
{
    Pending = 0,
    Approved = 1,
    Inprocess = 2,
    Inmediation = 3,
    Rejected = 4,
    Cancelled = 5,
    Refunded = 6,
    Chargedback = 7,
    StatusNotFounded = 8,
    CancelledByUser = 9,
    CancelledByMercadoPago = 10,
    CancelledByMercadoPagoPendingChargedback = 11,
    RefundedByMercadoPago = 12,
    TimeOut = 13,
    StatusCompraTest = 9999999,
    StatusCompraTestSystem = 99999999,
}

export const StatusCompraMapping = {
    [StatusCompraEnum.Pending]: "Pendente",
    [StatusCompraEnum.Approved]: "Aprovado",
    [StatusCompraEnum.Inprocess]: "Processando",
    [StatusCompraEnum.Inmediation]: "Intermediado",
    [StatusCompraEnum.Rejected]: "Rejeitado",
    [StatusCompraEnum.Cancelled]: "Cancelado",
    [StatusCompraEnum.Refunded]: "Reembolsado",
    [StatusCompraEnum.Chargedback]: "Estornado",
    [StatusCompraEnum.StatusNotFounded]: "Não encontrado",
    [StatusCompraEnum.CancelledByUser]: "Cancelado pelo usuário",
    [StatusCompraEnum.CancelledByMercadoPago]: "Cancelado pelo Mercado Pago",
    [StatusCompraEnum.CancelledByMercadoPagoPendingChargedback]: "Cancelado pelo Mercado Pago, estorno pendente",
    [StatusCompraEnum.RefundedByMercadoPago]: "Reenbolsado pelo mercado pago",
    [StatusCompraEnum.TimeOut]: "Prazo expirado",
    [StatusCompraEnum.StatusCompraTest]: "Teste",
    [StatusCompraEnum.StatusCompraTestSystem]: "Teste do sistema",
}